image: vyo2003/ubuntu-boost

stages:
  - test

test:
  stage: test
  script:
    - apt update -y
    - apt install -y git build-essential clang cppcheck clang-tidy
    - git clone https://github.com/google/googletest ./BinaryTree/googletest
    - make
